/content/documents/gogreen/products:
  .meta:order-before: newsfacets
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 92411640-5e18-4d25-b198-3debe3d15a33
  hippostd:foldertype: [new-product-folder, new-product-document]
  hippotranslation:id: 92dce99c-8e75-45ff-b624-c9e2b6a959b7
  hippotranslation:locale: en
  /solar-centurian---outdoor-security-light:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: 37a3ee3f-aa50-4068-8c2c-74619b6439f2
    hippo:name: Solar Centurian - Outdoor Security Light
    hippo:versionHistory: 7463b4e0-a6c8-4d2f-82bc-2fb15685b160
    /solar-centurian---outdoor-security-light[1]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: bd28b26d-6142-4217-a179-60efbb2e7e38
      gogreen:introduction: Light up your night with a solar powered, motion detected
        outdoor security light!
      gogreen:price: 74.0
      gogreen:title: Solar Centurian - Outdoor Security Light
      hippo:availability: []
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2019-11-25T14:22:26.405-08:00
      hippostdpubwf:lastModificationDate: 2019-11-25T14:22:26.406-08:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: eca2e75f-a615-4c83-a343-b5f03c97a07f
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>This solar powered light is a bright (over 600 lumen) Halogen Security Light that installs easily where utility wiring is impractical or expensive. A patented passive infrared motion detector is able to detect activity up to 23m/75 feet away controls the light. When activated, the Solar Centurion throws a flood light into the target area for up to 3 minutes or as long as there is movement in the area.</p>

          <p>It is perfect for security lighting or convenience lighting in your yard, at your garage, around your garage, or wherever security lighting is required at night!</p>

          <p>The light is replaceable at any lighting or hardware store (Sylvania 1995/ERK miniature Halogen Lamp).</p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: a44210bc-cee3-4989-a05d-629d6a938eee
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /solar-centurian---outdoor-security-light[2]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: 7923b024-b3fd-40b7-81ba-a719480d4be7
      gogreen:introduction: Light up your night with a solar powered, motion detected
        outdoor security light!
      gogreen:price: 74.0
      gogreen:title: Solar Centurian - Outdoor Security Light
      hippo:availability: [preview]
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2019-11-25T14:22:26.405-08:00
      hippostdpubwf:lastModificationDate: 2019-11-25T14:22:59.150-08:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: eca2e75f-a615-4c83-a343-b5f03c97a07f
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>This solar powered light is a bright (over 600 lumen) Halogen Security Light that installs easily where utility wiring is impractical or expensive. A patented passive infrared motion detector is able to detect activity up to 23m/75 feet away controls the light. When activated, the Solar Centurion throws a flood light into the target area for up to 3 minutes or as long as there is movement in the area.</p>

          <p>It is perfect for security lighting or convenience lighting in your yard, at your garage, around your garage, or wherever security lighting is required at night!</p>

          <p>The light is replaceable at any lighting or hardware store (Sylvania 1995/ERK miniature Halogen Lamp).</p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: a44210bc-cee3-4989-a05d-629d6a938eee
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /solar-centurian---outdoor-security-light[3]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 64a2199e-4fc4-4410-8ad4-e722f3cac94f
      gogreen:introduction: Light up your night with a solar powered, motion detected
        outdoor security light!
      gogreen:price: 74.0
      gogreen:title: Solar Centurian - Outdoor Security Light
      hippo:availability: [live]
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2019-11-25T14:22:26.405-08:00
      hippostdpubwf:lastModificationDate: 2019-11-25T14:22:59.150-08:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2019-11-25T14:23:03.436-08:00
      hippotranslation:id: eca2e75f-a615-4c83-a343-b5f03c97a07f
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>This solar powered light is a bright (over 600 lumen) Halogen Security Light that installs easily where utility wiring is impractical or expensive. A patented passive infrared motion detector is able to detect activity up to 23m/75 feet away controls the light. When activated, the Solar Centurion throws a flood light into the target area for up to 3 minutes or as long as there is movement in the area.</p>

          <p>It is perfect for security lighting or convenience lighting in your yard, at your garage, around your garage, or wherever security lighting is required at night!</p>

          <p>The light is replaceable at any lighting or hardware store (Sylvania 1995/ERK miniature Halogen Lamp).</p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: a44210bc-cee3-4989-a05d-629d6a938eee
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
  /lifeproof-nuud-ipad-air-case:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: ccadaa58-b476-4247-ae96-281747912a92
    hippo:name: Lifeproof nüüd IPad Air Case
    hippo:versionHistory: e1fa737e-cd57-4dd2-a8f6-4dd039364cd5
    /lifeproof-nuud-ipad-air-case[1]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: c18a2b11-aded-4eb5-9402-13ba2165abe6
      gogreen:introduction: Get full protection for your phone in any wet, dirty or
        damp setting.The nuud case armours your iPad Air without putting anything
        between your fingertips and the touchscreen. An optical glass lens lets you
        see and use the screen with crystal clarity.
      gogreen:price: 129.0
      gogreen:title: Lifeproof nüüd IPad Air Case
      hippo:availability: []
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2019-11-25T14:23:15.683-08:00
      hippostdpubwf:lastModificationDate: 2019-11-25T14:23:15.683-08:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: e5cba3df-9e46-4f12-9428-fc2dbb66099b
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <ul>
           <li>Waterproof, fully submersible to 2 metres for up to 1 hour.</li>
           <li>Shockproof, survives drops from 2 metres.</li>
           <li>Full access to touchscreen and all buttons, ports and controls.</li>
           <li>Maximum sound output and clarity.</li>
           <li>Anti-reflective optical-glass camera lens.</li>
           <li>Dimensions are 261.6 x 188 x 17.8mm.</li>
           <li>The LifeProof warranty and MEC's Rocksolid Guarantee cover this case itself. Neither guarantee covers the contents you put inside the case.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023">http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 2b703f17-f072-4b18-8cf3-18da62e1e8e0
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /lifeproof-nuud-ipad-air-case[2]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: 8360522e-2ddf-4a2a-9b50-20482be1cde7
      gogreen:introduction: Get full protection for your phone in any wet, dirty or
        damp setting.The nuud case armours your iPad Air without putting anything
        between your fingertips and the touchscreen. An optical glass lens lets you
        see and use the screen with crystal clarity.
      gogreen:price: 129.0
      gogreen:title: Lifeproof nüüd IPad Air Case
      hippo:availability: [preview]
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2019-11-25T14:23:15.683-08:00
      hippostdpubwf:lastModificationDate: 2019-11-25T14:24:04.572-08:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: e5cba3df-9e46-4f12-9428-fc2dbb66099b
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <ul>
           <li>Waterproof, fully submersible to 2 metres for up to 1 hour.</li>
           <li>Shockproof, survives drops from 2 metres.</li>
           <li>Full access to touchscreen and all buttons, ports and controls.</li>
           <li>Maximum sound output and clarity.</li>
           <li>Anti-reflective optical-glass camera lens.</li>
           <li>Dimensions are 261.6 x 188 x 17.8mm.</li>
           <li>The LifeProof warranty and MEC's Rocksolid Guarantee cover this case itself. Neither guarantee covers the contents you put inside the case.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023">http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 2b703f17-f072-4b18-8cf3-18da62e1e8e0
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /lifeproof-nuud-ipad-air-case[3]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: c4012161-ea5f-4a86-b74d-1d9485cadc22
      gogreen:introduction: Get full protection for your phone in any wet, dirty or
        damp setting.The nuud case armours your iPad Air without putting anything
        between your fingertips and the touchscreen. An optical glass lens lets you
        see and use the screen with crystal clarity.
      gogreen:price: 129.0
      gogreen:title: Lifeproof nüüd IPad Air Case
      hippo:availability: [live]
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2019-11-25T14:23:15.683-08:00
      hippostdpubwf:lastModificationDate: 2019-11-25T14:24:04.572-08:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2019-11-25T14:24:05.990-08:00
      hippotranslation:id: e5cba3df-9e46-4f12-9428-fc2dbb66099b
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <ul>
           <li>Waterproof, fully submersible to 2 metres for up to 1 hour.</li>
           <li>Shockproof, survives drops from 2 metres.</li>
           <li>Full access to touchscreen and all buttons, ports and controls.</li>
           <li>Maximum sound output and clarity.</li>
           <li>Anti-reflective optical-glass camera lens.</li>
           <li>Dimensions are 261.6 x 188 x 17.8mm.</li>
           <li>The LifeProof warranty and MEC's Rocksolid Guarantee cover this case itself. Neither guarantee covers the contents you put inside the case.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023">http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 2b703f17-f072-4b18-8cf3-18da62e1e8e0
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
  /mec-lodge-4-4-tent:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: 14b3f527-5ff1-49d3-8c08-cf95517d1ff2
    hippo:name: MEC Lodge 4+4 Tent
    hippo:versionHistory: 32519124-0ee8-4c6b-a30a-366a08965c12
    /mec-lodge-4-4-tent[1]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 19fa1382-3f16-4ee4-9666-f62f44f6b82a
      gogreen:introduction: Glamping, anyone? This large tent has 2 bedrooms that
        each sleep 2 people. Both rooms are accessed from a central hall that’s tall
        enough to stand up in. The hall doesn't have a floor, so you can use it to
        deal with wet gear without getting your sleeping bags wet or gritty. Store
        your bikes in it, dry your wetsuit, or use it as a sheltered dining area.
        An optional ground sheet converts the hall to a bedroom that sleeps up to
        4 additional campers.
      gogreen:price: 589.0
      gogreen:title: MEC Lodge 4+4 Tent
      hippo:availability: []
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2019-11-25T14:24:13.610-08:00
      hippostdpubwf:lastModificationDate: 2019-11-25T14:24:13.610-08:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 9ab055f6-0332-4e49-beeb-347e59a905d0
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <ul>
           <li>Central hall has doors with zippable mesh ventilation at either end.</li>
           <li>Hall has numerous hanging points for drying lines or lanterns.</li>
           <li>Each 2-person room has double pockets.</li>
           <li>Hall has 4 storage pockets.</li>
           <li>Optional floor for central hall available separately.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858">http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4374b378-8794-4c8c-84f4-21bf89bc10db
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /mec-lodge-4-4-tent[2]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: e0d2facd-5e1e-4f0d-89c8-69c40b392826
      gogreen:introduction: Glamping, anyone? This large tent has 2 bedrooms that
        each sleep 2 people. Both rooms are accessed from a central hall that’s tall
        enough to stand up in. The hall doesn't have a floor, so you can use it to
        deal with wet gear without getting your sleeping bags wet or gritty. Store
        your bikes in it, dry your wetsuit, or use it as a sheltered dining area.
        An optional ground sheet converts the hall to a bedroom that sleeps up to
        4 additional campers.
      gogreen:price: 589.0
      gogreen:title: MEC Lodge 4+4 Tent
      hippo:availability: [preview]
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2019-11-25T14:24:13.610-08:00
      hippostdpubwf:lastModificationDate: 2019-11-25T14:27:42.519-08:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 9ab055f6-0332-4e49-beeb-347e59a905d0
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <ul>
           <li>Central hall has doors with zippable mesh ventilation at either end.</li>
           <li>Hall has numerous hanging points for drying lines or lanterns.</li>
           <li>Each 2-person room has double pockets.</li>
           <li>Hall has 4 storage pockets.</li>
           <li>Optional floor for central hall available separately.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858">http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4374b378-8794-4c8c-84f4-21bf89bc10db
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /mec-lodge-4-4-tent[3]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: a438ddca-5229-4325-9367-103ec562a051
      gogreen:introduction: Glamping, anyone? This large tent has 2 bedrooms that
        each sleep 2 people. Both rooms are accessed from a central hall that’s tall
        enough to stand up in. The hall doesn't have a floor, so you can use it to
        deal with wet gear without getting your sleeping bags wet or gritty. Store
        your bikes in it, dry your wetsuit, or use it as a sheltered dining area.
        An optional ground sheet converts the hall to a bedroom that sleeps up to
        4 additional campers.
      gogreen:price: 589.0
      gogreen:title: MEC Lodge 4+4 Tent
      hippo:availability: [live]
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2019-11-25T14:24:13.610-08:00
      hippostdpubwf:lastModificationDate: 2019-11-25T14:27:42.519-08:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2019-11-25T14:27:44.005-08:00
      hippotranslation:id: 9ab055f6-0332-4e49-beeb-347e59a905d0
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <ul>
           <li>Central hall has doors with zippable mesh ventilation at either end.</li>
           <li>Hall has numerous hanging points for drying lines or lanterns.</li>
           <li>Each 2-person room has double pockets.</li>
           <li>Hall has 4 storage pockets.</li>
           <li>Optional floor for central hall available separately.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858">http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4374b378-8794-4c8c-84f4-21bf89bc10db
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
